#if !canImport(ObjectiveC)
import XCTest

extension CGPointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CGPointTests = [
        ("testPoints", testPoints),
    ]
}

extension HolePolygonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HolePolygonTests = [
        ("testInnerLineSegments", testInnerLineSegments),
        ("testMiddleLineSegments", testMiddleLineSegments),
        ("testOuterLineSegments", testOuterLineSegments),
        ("testPointsInPolygon", testPointsInPolygon),
    ]
}

extension InvalidPolygonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InvalidPolygonTests = [
        ("testEmptyPolygon", testEmptyPolygon),
        ("testLineSegmentPolygon", testLineSegmentPolygon),
    ]
}

extension LineSegmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LineSegmentTests = [
        ("testHorizontalIntercepts", testHorizontalIntercepts),
        ("testRightwardRayIntersection", testRightwardRayIntersection),
        ("testSlopes", testSlopes),
        ("testYAxisIntercepts", testYAxisIntercepts),
    ]
}

extension PointInPolygonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PointInPolygonTests = [
        ("testClosingPolygons", testClosingPolygons),
    ]
}

extension PolygonBoundaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PolygonBoundaryTests = [
        ("testPointIsOnBoundary", testPointIsOnBoundary),
    ]
}

extension SelfIntersectingPolygonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SelfIntersectingPolygonTests = [
        ("testContainsBoundaryPoints", testContainsBoundaryPoints),
        ("testContainsPointsInsideBoundingBoxOutsidePolygon", testContainsPointsInsideBoundingBoxOutsidePolygon),
        ("testContainsPointsInsidePolygon", testContainsPointsInsidePolygon),
        ("testLineSegments", testLineSegments),
    ]
}

extension SimplePolygonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SimplePolygonTests = [
        ("testBoundingBox", testBoundingBox),
        ("testContainsBoundaryPoints", testContainsBoundaryPoints),
        ("testContainsPointInsideBoundingBoxOutsidePolygon", testContainsPointInsideBoundingBoxOutsidePolygon),
        ("testContainsPointsInsidePolygons", testContainsPointsInsidePolygons),
        ("testContainsPointsOutsideBoundingBoxAndPolygon", testContainsPointsOutsideBoundingBoxAndPolygon),
        ("testSquareLineSegments", testSquareLineSegments),
        ("testTriangleLineSegments", testTriangleLineSegments),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CGPointTests.__allTests__CGPointTests),
        testCase(HolePolygonTests.__allTests__HolePolygonTests),
        testCase(InvalidPolygonTests.__allTests__InvalidPolygonTests),
        testCase(LineSegmentTests.__allTests__LineSegmentTests),
        testCase(PointInPolygonTests.__allTests__PointInPolygonTests),
        testCase(PolygonBoundaryTests.__allTests__PolygonBoundaryTests),
        testCase(SelfIntersectingPolygonTests.__allTests__SelfIntersectingPolygonTests),
        testCase(SimplePolygonTests.__allTests__SimplePolygonTests),
    ]
}
#endif
