name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macos:
    name: Build and Test (macOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run Tests
      run: swift test -v
    - name: Generate Code Coverage Reports
      run: xcodebuild -scheme PointInPolygon-Package -project PointInPolygon.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' build test
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      
  linux:
    name: Build and Test (Linux)
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Swift
      uses: sersoft-gmbh/SwiftyActions@v1
      with:
        release-version: 5.3.3
        platform: ubuntu-20.04
    - name: Build
      run: swift build -v
    - name: Run Tests
      run: swift test -v
